version: '3.8'

services:
  price-comparison-api:
    build: .
    container_name: price-comparison-api
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      - CACHE_TTL_SECONDS=3600
      - REQUEST_TIMEOUT=30
      - MAX_CONCURRENT_REQUESTS=5
    volumes:
      - ./api_cache:/app/api_cache
      - ./logs:/app/logs
      - ./webpages_samples:/app/webpages_samples:ro  # Read-only mount for HTML samples
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: price-comparison-network
